language: python
sudo: required
dist: trusty

install:
  - pip install -r requirements.txt
  - nvm install stable
  - npm install

before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb

script:
 - nosetests --with-coverage --cover-package=project
 - npm test

notifications:
  email: false