"""empty message

Revision ID: 4c072c47d632
Revises: 28948eaebd65
Create Date: 2016-07-10 00:17:33.940561

"""

# revision identifiers, used by Alembic.
revision = '4c072c47d632'
down_revision = '28948eaebd65'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('show_completed_task', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'show_completed_task')
    ### end Alembic commands ###
