"""empty message

Revision ID: ac1a959992e9
Revises: 4dfc15721b46
Create Date: 2016-07-08 19:47:25.972897

"""

# revision identifiers, used by Alembic.
revision = 'ac1a959992e9'
down_revision = '4dfc15721b46'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('category', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'category')
    ### end Alembic commands ###
